
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: teeball_five_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: teeball_five_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: teeball_five_production
  username: teeball_five
  password: <%= ENV["TEEBALL_FIVE_DATABASE_PASSWORD"] %>
